#!/usr/bin/env php
<?php

use Midnight\DependencyAnalyzer\Command\AnalyzeCommand;
use Symfony\Component\Console\Application;

const POSSIBLE_AUTOLOAD_PATHS = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
];

foreach (POSSIBLE_AUTOLOAD_PATHS as $file) {
    if (!file_exists($file)) {
        continue;
    }
    require_once $file;
}

$app = new Application('Dependency Analyzer');
$analyzeCommand = new AnalyzeCommand();
$app->add($analyzeCommand);
$analyzeCommandName = $analyzeCommand->getName();
if ($analyzeCommandName !== null) {
    $app->setDefaultCommand($analyzeCommandName);
}
$app->run();
